import type { TaxPlatform } from "./types";

const platformMappings: Record<TaxPlatform, Record<string, string>> = {
  koinly: {
    transfer: "transfer",
    swap: "exchange",
    deposit: "deposit",
    withdraw: "withdrawal",
    approve: "cost",
    claim: "reward",
    stake: "stake",
    unstake: "unstake",
    mint: "receive",
    burn: "send",
    bridge: "transfer",
    borrow: "borrow",
    repay: "repay",
    "liquidity-add": "send",
    "liquidity-remove": "receive",
  },
  cointracker: {
    transfer: "Transfer",
    swap: "Trade",
    deposit: "Receive",
    withdraw: "Send",
    approve: "Send",
    claim: "Receive",
    stake: "Send",
    unstake: "Receive",
    mint: "Receive",
    burn: "Send",
    bridge: "Transfer",
    borrow: "Receive",
    repay: "Send",
    "liquidity-add": "Send",
    "liquidity-remove": "Receive",
  },
  coinledger: {
    transfer: "Transfer",
    swap: "Trade",
    deposit: "Deposit",
    withdraw: "Withdrawal",
    approve: "Other Fee",
    claim: "Airdrop",
    stake: "Staking",
    unstake: "Unstaking",
    mint: "Receive",
    burn: "Send",
    bridge: "Transfer",
    borrow: "Borrow",
    repay: "Repay",
    "liquidity-add": "Send",
    "liquidity-remove": "Receive",
  },
  taxbit: {
    transfer: "Transfer",
    swap: "Exchange",
    deposit: "Income",
    withdraw: "Sale",
    approve: "Expense",
    claim: "Income",
    stake: "Transfer Out",
    unstake: "Transfer In",
    mint: "Income",
    burn: "Expense",
    bridge: "Transfer",
    borrow: "Transfer In",
    repay: "Transfer Out",
    "liquidity-add": "Transfer Out",
    "liquidity-remove": "Transfer In",
  },
  tokentax: {
    transfer: "Transfer",
    swap: "Trade",
    deposit: "Deposit",
    withdraw: "Withdrawal",
    approve: "Spend",
    claim: "Income",
    stake: "Staking",
    unstake: "Unstaking",
    mint: "Mining",
    burn: "Spend",
    bridge: "Transfer",
    borrow: "Borrow",
    repay: "Repay",
    "liquidity-add": "Spend",
    "liquidity-remove": "Income",
  },
  accointing: {
    transfer: "deposit",
    swap: "order",
    deposit: "deposit",
    withdraw: "withdraw",
    approve: "fee",
    claim: "airdrop",
    stake: "withdraw",
    unstake: "deposit",
    mint: "deposit",
    burn: "withdraw",
    bridge: "deposit",
    borrow: "deposit",
    repay: "withdraw",
    "liquidity-add": "withdraw",
    "liquidity-remove": "deposit",
  },
  zenledger: {
    transfer: "Transfer",
    swap: "Trade",
    deposit: "Receive",
    withdraw: "Send",
    approve: "Fee",
    claim: "Airdrop",
    stake: "Staking",
    unstake: "Staking",
    mint: "Receive",
    burn: "Send",
    bridge: "Transfer",
    borrow: "Receive",
    repay: "Send",
    "liquidity-add": "Send",
    "liquidity-remove": "Receive",
  },
  "crypto-tax-calculator": {
    transfer: "transfer",
    swap: "sell",
    deposit: "receive",
    withdraw: "send",
    approve: "fee",
    claim: "airdrop",
    stake: "staking-deposit",
    unstake: "staking-withdrawal",
    mint: "receive",
    burn: "send",
    bridge: "bridge-transfer",
    borrow: "borrow",
    repay: "loan-repayment",
    "liquidity-add": "liquidity-in",
    "liquidity-remove": "liquidity-out",
  },
  "tres-finance": {
    transfer: "token_transfer",
    swap: "token_transfer",
    deposit: "token_transfer",
    withdraw: "token_transfer",
    approve: "gas",
    claim: "token_transfer",
    stake: "token_transfer",
    unstake: "token_transfer",
    mint: "token_transfer",
    burn: "token_transfer",
    bridge: "token_transfer",
    borrow: "token_transfer",
    repay: "token_transfer",
    "liquidity-add": "token_transfer",
    "liquidity-remove": "token_transfer",
  },
  cryptio: {
    transfer: "withdraw",
    swap: "trade",
    deposit: "deposit",
    withdraw: "withdraw",
    approve: "withdraw",
    claim: "deposit",
    stake: "withdraw",
    unstake: "deposit",
    mint: "deposit",
    burn: "withdraw",
    bridge: "withdraw",
    borrow: "deposit",
    repay: "withdraw",
    "liquidity-add": "withdraw",
    "liquidity-remove": "deposit",
  },
};

export function mapTxType(platform: TaxPlatform, octavType: string): string {
  return platformMappings[platform]?.[octavType] ?? octavType;
}
